Repository uc-cdis/gen3-gitops, pull requests merged in 2025-07, with the labels that each got.

#325 Remove Ambassador, Hatchery, manifestservice, sower and WTS from midrc staging
  .secrets.baseline
  midrcprod/staging.midrc.org/values/values.yaml
Labels: TestDicomViewer, TestAggregateMDS

#326 Remove Ambassador, Hatchery, manifestservice, sower and wts from validate staging
  .secrets.baseline
  midrcvalidate/validatestaging.midrc.org/values/values.yaml
Labels: TestDataUpload, TestGoogleDataAccess, TestDbgap, TestGraphSubmitAndQuery

#331 Remove ambassador, manifestservice, hartchery, sower and wts from `validate.midrc.org`, update services to `2025.06`
  .secrets.baseline
  midrcvalidate/validate.midrc.org/values/values.yaml
Labels: TestHomePage

#342 Update PreProd BDC DD in values.yaml
  bdcatprod/preprod.gen3.biodatacatalyst.nhlbi.nih.gov/values/values.yaml
Labels: TestGoogleDataAccess, TestGuppyService

#338 Applying version 2025.07 to data.midrc.org
  midrcprod/data.midrc.org/values/values.yaml
Labels: TestHomePage

#330 Gen3 Monthly Release `2025.07` to imaging-hub.data-commons.org
  bihprod/imaging-hub.data-commons.org/values/values.yaml
Labels: TestHomePage

#354 Re-add workspaces in MIDRC Prod
  .secrets.baseline
  midrcprod/data.midrc.org/values/values.yaml
Labels: TestHomePage
