Repository uc-cdis/gen3-gitops, pull requests merged in 2025-09, with the labels that each got.

#552 Gen3 Monthly Release 2025.09 1756825822
  healprod/externaldata.healdata.org/values/values.yaml
Labels: TestDbgap, TestAuditService, TestUserToken, TestCentralizedAuth

#538 Update values.yaml to 2025.08 release
  .secrets.baseline
  covid19prod/chicagoland.pandemicresponsecommons.org/values/portal/css/gitops.css
  covid19prod/chicagoland.pandemicresponsecommons.org/values/portal/gitops.json
  covid19prod/chicagoland.pandemicresponsecommons.org/values/portal/logo/gitops-logo.png
  covid19prod/chicagoland.pandemicresponsecommons.org/values/portal/sponsors/gitops-sponsors/OCC-data.png
  covid19prod/chicagoland.pandemicresponsecommons.org/values/portal/sponsors/gitops-sponsors/awswhite.png
  covid19prod/chicagoland.pandemicresponsecommons.org/values/portal/sponsors/gitops-sponsors/covid_gene.svg
  covid19prod/chicagoland.pandemicresponsecommons.org/values/portal/sponsors/gitops-sponsors/logo_bioteam_400px.png
  covid19prod/chicagoland.pandemicresponsecommons.org/values/portal/sponsors/gitops-sponsors/occHORIZwhitetitleTRANS.png
  covid19prod/chicagoland.pandemicresponsecommons.org/values/values.yaml
Labels: TestHomePage

#553 Gen3 Monthly Release 2025.09 1756825825
  brhprod/brh.data-commons.org/values/values.yaml
Labels: TestWorkspacePage

#529 Disable hatchery-reaper in CI
  ci/default/values/hatchery.yaml
Labels: TestWorkspacePage

#595 Update manifestservice.yaml
  ci/default/values/manifestservice.yaml
Labels: TestManifestService

#594 Update values.yaml
  jcoinprod/jcoin.datacommons.io/values/values.yaml
Labels: TestWorkspacePage, TestDataUpload

#613 Add Hotnode to data.midrc.org
  .secrets.baseline
  midrcprod/data.midrc.org/values/values.yaml
Labels: TestHomePage

#633 Update fence to 11.4.0 in MIDRC prod
  midrcprod/data.midrc.org/values/values.yaml
Labels: TestHomePage

#625 Gen3 Monthly Release 2025.09 midrcprod/staging.midrc.org 1757955733
  .secrets.baseline
  midrcprod/staging.midrc.org/values/portal/css/gitops.css
  midrcprod/staging.midrc.org/values/portal/gitops.json
  midrcprod/staging.midrc.org/values/portal/logo/gitops-logo.png
  midrcprod/staging.midrc.org/values/values.yaml
Labels: TestHomePage

#655 Update BRH staging values.yaml (welcome files and notebook changes)
  brhprod/brhstaging.data-commons.org/values/values.yaml
Labels: TestCentralizedAuth

#615 Gen3 Monthly Release 2025.09 covid19prod/chicagoland.pandemicresponsecommons.org 1757703425
  covid19prod/chicagoland.pandemicresponsecommons.org/values/values.yaml
Labels: TestHomePage

#629 Gen3 Monthly Release 2025.09 bihprod/bih-staging.data-commons.org 1757955790
  .secrets.baseline
  bihprod/bih-staging.data-commons.org/values/portal/gitops.json
  bihprod/bih-staging.data-commons.org/values/portal/logo/gitops-logo.png
  bihprod/bih-staging.data-commons.org/values/portal/sponsors/gitops-sponsors/gene_bgy.svg
  bihprod/bih-staging.data-commons.org/values/values.yaml
Labels: TestHomePage

#627 Gen3 Monthly Release 2025.09 midrcvalidate/validatestaging.midrc.org 1757955753
  .secrets.baseline
  midrcvalidate/validatestaging.midrc.org/values/portal/css/gitops.css
  midrcvalidate/validatestaging.midrc.org/values/portal/gitops.json
  midrcvalidate/validatestaging.midrc.org/values/portal/logo/gitops-logo.png
  midrcvalidate/validatestaging.midrc.org/values/values.yaml
Labels: TestHomePage

#674 Add workspace registration in MIDRC Prod
  .secrets.baseline
  midrcprod/data.midrc.org/values/values.yaml
Labels: TestGraphSubmitAndQuery

#628 Gen3 Monthly Release 2025.09 bihprod/imaging-hub.data-commons.org 1757955764
  .secrets.baseline
  bihprod/imaging-hub.data-commons.org/values/portal/gitops.json
  bihprod/imaging-hub.data-commons.org/values/portal/logo/gitops-logo.png
  bihprod/imaging-hub.data-commons.org/values/portal/sponsors/gitops-sponsors/gene_bgy.svg
  bihprod/imaging-hub.data-commons.org/values/values.yaml
Labels: TestHomePage

#697 Update values.yaml to bump up portal in midrcprod
  midrcprod/data.midrc.org/values/values.yaml
Labels: TestETL, TestWorkspacePage, TestHomePage, TestDataUpload, TestDbgap, TestUserToken, TestLoginPage, TestDrsEndpoints, TestPresignedURL, TestOIDCClient, TestGen3Client, TestCentralizedAuth, TestClientCredentials, TestRequestor
