Repository uc-cdis/gen3-gitops, pull requests merged in 2025-08, with the labels that each got.

#377 Update Dictionary and ETL Mapping for CI Default
  ci/default/values/etl.yaml
  ci/default/values/values.yaml
Labels: TestHomePage

#403 fix(fence): bump
  bdcatprod/gen3.biodatacatalyst.nhlbi.nih.gov/values/values.yaml
Labels: TestDataUpload

#431 update BDC Prod dd
  bdcatprod/gen3.biodatacatalyst.nhlbi.nih.gov/values/values.yaml
Labels: TestAggregateMDS

#439 updating midrc-staging dd to version 1.4.0
  midrcprod/staging.midrc.org/values/values.yaml
Labels: TestHomePage

#433 Update fence version for VPODC
  vadcprod/vpodc.data-commons.org/values/values.yaml
Labels: TestETL, TestWorkspacePage, TestHomePage, TestDataUpload, TestDbgap, TestGraphSubmitAndQuery, TestAuditService, TestUserToken, TestLoginPage

#440 Add PopSci Bucket to DCF Staging
  dcf-staging/nci-crdc-staging.datacommons.io/values/values.yaml
Labels: TestDataUpload

#481 Add KF Buckets to Production
  dcfprod/nci-crdc.datacommons.io/values/values.yaml
Labels: TestDataUpload

#495 Update values.yaml
  dcfprod/nci-crdc.datacommons.io/values/values.yaml
Labels: TestHomePage, TestDataUpload, TestLoginPage

#514 Adding PDB for Postgres and Elasticsearch
  ci/default/values/values.yaml
Labels: TestPFBExport

#499 Gen3 Monthly Release 2025.08 to imaging-hub.data-commons.org
  .secrets.baseline
  bihprod/imaging-hub.data-commons.org/values/values.yaml
Labels: TestHomePage

#497 Gen3 Monthly Release `2025.08` to `validate.midrc.org`
  .secrets.baseline
  midrcvalidate/validate.midrc.org/values/values.yaml
Labels: TestHomePage
